vega/vega-tooltip

- .gitignore
- README.md
- docs/APIs.md
- docs/creating_your_tooltip.md
- docs/customizing_your_tooltip.md
- examples.js
- index.html
- package.json
- src/vg-tooltip.css
- src/vg-tooltip.js
Renamed package name to `vega-tooltip` in code and documentation.
Added a temporary fix for timeUnit template (to make examples in this PR work). We will use template for all time fields in a different PR.
> Rename vega-lite-tooltip to vega-tooltip. Fix #42.

- exampleSpecs/overlay_area_full.json
- exampleSpecs/overlay_area_short.json
- exampleSpecs/overlay_line_full.json
- exampleSpecs/overlay_line_short.json
- examples.js
- index.html
- src/vg-tooltip.js
Please merge #46 first. Branch-wise difference: https://github.com/vega/vega-tooltip/compare/zqu/rename...zqu/tooltip-on-layers
Tooltip is now working with `overlay` config for `line` and `area`. Fix #47 
For line chart, when hovering on the points, we get all fields in tooltip:
When hovering on the line, we only get the string and boolean fields in tooltip:
Similarly, when hovering on the points on top of an area, we get all fields:
When hovering on the area itself, we only get the string and boolean fields:
> Tooltip on overlay line charts and area charts

- docs/APIs.md
- examples.js
- src/vg-tooltip.js
`vl.tooltip(vgView, vlSpec).destroy()` and `vg.tooltip(vgView).destroy()` now removes event listners on the `vgView`
> Add .destroy() for removing event listeners on vgView Fix #55

- docs/APIs.md
- src/vg-tooltip.js
Allow user to provide `onInit`, `onUpdate` and `onClear` callbacks through `options`
- This makes sure that user-provided callbacks only get called on items that actually has tooltip. If it's some random chart element that doesn't deserve a tooltip, we don't call user-provided callbacks.
> Accept onAppear, onMove, onDisappear callbacks through options

- docs/APIs.md
- examples.js
- src/vg-tooltip.css
- src/vg-tooltip.js
> Add delay in tooltip

- src/vg-tooltip.js
Fig.1
Fig.2
Fig.3
Better display temporal fields in tooltip (with or without timeUnit). Fix #54
> Better display temporal fields in tooltip (with or without timeUnit)

- docs/creating_your_tooltip.md
- examples.js
- Add a code example of using `vg.tooltip` in `vg.embed` context in documentation
- console log error if `vg.parse.spec` has error
> Document vg.tooltip usage in vg.embed context. Fix #70

- exampleSpecs/bar_layered_transparent.json
- exampleSpecs/scatter_binned.json
- exampleSpecs/trellis_barley.json
- index.html
- package.json
- src/index.ts
- yarn.lock
- fix the cannot find field error with bin fields due to vega API change
- ignores the display for the `nested-main-group` scenegraph, which represents the blank tiles
> Fix bin fields cannot found and ignores the blank space scenegraph

- examples.css
- examples.js
- index.html
- src/formatFieldValue.ts
- src/index.ts
- src/options.ts
- src/parseOption.ts
- src/supplementField.ts
- src/supplementedFieldOption.ts
- src/tooltipDisplay.ts
- vega-examples.html
- vega-examples.js
- vega-lite-examples.html
- vega-lite-examples.js
- split file into `parseOption.ts`, `formatFieldValue.ts`, `supplementField.ts` and `supplementField.ts` based on semantics.
- combine all the typings declaration into one `options.ts`
> split file into modules and combine all typing declaration

- package.json
- src/index.ts
- src/parseOption.ts
- src/supplementField.ts
- vega-lite-examples.js
- yarn.lock
- remove d3 map
- refactor a little more
- create a copy of options before supplement it, thus preventing causing side-effect to the original object
> Remove d3 map

- src/parseOption.ts
Fix #123
`nested_main_group` was the old name for faceted plot, but this is no longer true for VL2.  I think we don't really need to check name as we should not show tooltip for group marks anyway.
> Do not show tooltip for group marks

- docs/APIs.md
- src/index.ts
- src/options.ts
- src/parseOption.ts
- src/supplementField.ts
- Stop-gap fix for #108 and #39 by suppressing the warnings on missing fields in composite spec
> Suppress warnings if the spec is composition

- src/index.ts
Empty string shows an empty box, even though the expectation is that it's not shown.
> hide tooltip on empty string

- src/defaults.ts
Editor with `vega-tooltip v0.10.1` error fix.
> Append `toString` to `defaultStyle`

- .autorc.json
- .github/workflows/merge-dependabot.yml
- .github/workflows/publish.yml
- README.md
- package.json
- yarn.lock
- Unified versioning / release process through the Vega org: 
- less time spent spent to rebuild packages locally/releasing/managing changelogs = more time for new features
- Replicate the setup in https://github.com/vega/ts-json-schema-generator/pull/856, + updates documentation
- Needed to switch to json-based config because something about the TSconfig / eslint settings weren't playing nicely with a JS based configuration file. Might revisit this later once I have a clearer idea of what Beemo is doing (haven't used it before).
- Pinned `723f22c3b9fec8705988dcba0802e6df9cbb4d82` to `stable`
- Documented guidelines re: merging strategies
- Notes: https://rietta.com/blog/github-merge-types/
- CI should pass
<details>
<summary>📦 Published PR as canary version: …
> chore: set up auto for versioning/release management 

- package.json
- Currently, merging `latest` -> `stable` bumps the library version for `stable`, but the `prerelease` branch keeps its old version number.
- The only impact of this for users is they might be confused if they download the `latest` tag, and see the package.json is older than they expect.
- We won't have to manually do this step after resolving https://github.com/intuit/auto/issues/2047
> chore: sync prerelease branch version with stable

- src/Handler.ts
> fix: only append tooltip element to container once

- .github/workflows/publish.yml
<details>
<summary>📦 Published PR as canary version: <code>0.28.1--canary.687.3e8dda7.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install vega-tooltip@0.28.1--canary.687.3e8dda7.0
yarn add vega-tooltip@0.28.1--canary.687.3e8dda7.0
```
</details>
> chore: remove `NODE_AUTH_TOKEN`

- README.md
- src/Handler.ts
For sites with Content Security Policies that do not feature the `unsafe-inline` specification, it seems the more preferable approach for tooltip positioning is using the CSS Object Model method `.style`.
Currently, vega-tooltip uses `setAttribute` to adjust the tooltip positioning (top & left) at the same time - [here](https://github.com/vega/vega-tooltip/blob/7e2b7c0b4b75edabbc3afb292e05555ae1d7adef/src/Handler.ts#L89). This invokes the HTML parser and CSP inline checks are triggered, blocking the operation. When the tooltip positioning is directly adjusted via `.style.top` & `.style.left`, the operations successfully comply with a CSP directive of `style-src: self`.
Some discussion/context [here](https://github.com/w3c/webappsec-csp/issues/212)
> fix: update tooltip positioning for CSP

- vega-tooltip.scss
To resolve #739 as discussed there
> feat: remove limit on image size in tooltips

- docs/APIs.md
- src/Handler.ts
- src/defaults.ts
- src/formatValue.ts
For https://github.com/vega/vega-embed/pull/1286
> feat: baseURL for image paths

- examples/examples.css
- examples/vega-examples.html
- examples/vega-lite-examples.html
- package.json
- src/Handler.ts
- src/defaults.ts
- src/position.ts
- test/position.test.ts
Add options and support for snapping tooltips to the associated mark and set the position.
fixes #200 
```
Options {
...
anchor: 'cursor' | 'mark';
position: Postion | Position[];
}
type Position = 'top' | 'bottom' | 'left' | 'right' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
```
Each of the position options match the available `anchor` options on the [vega label transform](https://vega.github.io/vega/docs/transforms/label/).
Setting the `anchor = 'mark'` will make it so that the tooltip snaps to the associated mark. For `voronoi` paths, it will use the point that the voronoi path is derived from.
The tooltip will be positioned based on the `position` option. If only one position is provided, it will attempt to place the tooltip in that location. If the tooltip would be …
> feat: anchor tooltip to mark

- src/position.ts
- test/position.test.ts
It's possible for only `x` or `y` to be defined on a group item. The logic in place checked if both were defined and then summed their offsets. This fix checks them independently so that if only one or the other is defined, they are still summed up.
Validated against `@adobe/react-spectrum-charts` that this change fixes the bug I was seeing there.
A test has been added to verify and catch this.
> fix: mark position calculation when only x or y are defined
