vega/vega-tooltip

src/vg-tooltip.js

- In effect, in tooltip the default title for count fields used to be "count". Now the default title is "Number of Records", which is consistent with the vl chart.
PS: @kanitw when we were talking about this PR earlier, I put down a note that I should do "_initConfig in tooltip, not in vega-lite". However, in vega-lite there is no `_initConfig()` exported (there are private `_initConfig()` methods in `UnitModel`, `LayerModel` etc). Therefore, in this PR, I'm reading `vl.config.defaultConfig.countTitle` instead.

Support countTitle (default: "Number of Records") in tooltip

---

src/index.ts
src/options.ts
src/parseOption.ts
tsconfig.json

- add types `ScenegraphData` and `TemporaryFieldOption`
- set `key` property type to be string

Disable noImplicitAny

---

docs/creating_your_tooltip.md
yarn.lock

- fixes #116 and edit docs to reflect new specs.

edit docs to remove requirement for placeholder

---

docs/customizing_your_tooltip.md

Update example to use embed's promise instead of a callback.

vega-embed returns a promise (no more callback)

---

docs/creating_your_tooltip.md

Embed returns a promise, fix 2nd example.

---

tsconfig.json

Fix compile error

---

exampleSpecs/scatter.json
src/supplementField.ts
vega-lite-examples.js

- Fixes #75 and update examples to show that it uses axis title as default

Field title now uses custom axis title as default

---

exampleSpecs/histogram.json
src/parseOption.ts
src/supplementField.ts
vega-examples.html
vega-lite-examples.html
vega-lite-examples.js
yarn.lock

- fixes #129 
- Bin field will now be displayed as `Field name (binned): start-end` instead of two separate fields  `bin_Field_name` and `bin_Field_name_end`

Update tooltip to use recent vega-lite syntax

---

src/options.ts
yarn.lock

Remove literal key type ([key: string])

---

.travis.yml
package.json
src/formatFieldValue.ts
src/parseOption.ts
src/tooltipDisplay.ts

- add .travis.yml config for travis CI (copied from vega-editor repo)

Set up Travis CI

---

package.json

Fix https://github.com/vega/vega-tooltip/issues/173
Also sort the dev dependencies.

remove vega production dependency

---

src/position.ts

Addresses https://github.com/vega/vega-tooltip/issues/218

Change clientX/clientY to pageX/pageY to fix tooltip misplacement

---

vega-tooltip.scss

Delete unused css

---

docs/customizing_your_tooltip.md

Fix CSS in customization documentation

---

.travis.yml
README.md
docs/creating_your_tooltip.md
examples/specs/images.json
examples/vega-examples.html
examples/vega-lite-examples.html
src/formatValue.ts
tsconfig.src.json
vega-tooltip.scss

feat: support images in tooltips

---

src/Handler.ts

fixes #506
Thanks to https://github.com/dankrusi for the fix.

fix: support tooltips in fullscreen

---

test/Handler.test.ts

Adds basic Handler tests (will be added to in #557)
This is a first attempt at a test suite for this class; any suggestions welcome.

test: add test suite for Handler

---

build-style.sh
package.json
src/defaults.ts
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>0.28.0--canary.614.0a1f487.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install vega-tooltip@0.28.0--canary.614.0a1f487.0
yarn add vega-tooltip@0.28.0--canary.614.0a1f487.0
```
</details>

feat: switch to sass

---

.github/workflows/publish.yml
.github/workflows/test.yml

<details>
<summary>📦 Published PR as canary version: <code>0.28.1--canary.688.3450cec.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install vega-tooltip@0.28.1--canary.688.3450cec.0
yarn add vega-tooltip@0.28.1--canary.688.3450cec.0
```
</details>

chore: improve caching and token handling

---

.github/workflows/publish.yml
.github/workflows/test.yml
build-style.sh
package.json
rollup.config.js
src/Handler.ts
src/defaults.ts
yarn.lock

Revert "Release"

---

src/defaults.ts

Fixes https://github.com/vega/vega-tooltip/issues/1018

fix: update defaults.ts to fix custom EL_ID replacing logic
